"""
PDF Report Generator
Beautiful PDF exports for assessments, certificates, and reports
"""
import io
from datetime import datetime
from typing import Optional, Dict, Any, List
from dataclasses import dataclass

# ReportLab imports
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import qrcode
import os


@dataclass
class ReportData:
    """Data for report generation."""
    title: str
    subtitle: Optional[str] = None
    data: Dict[str, Any] = None
    tables: List[Dict] = None
    footer: str = "Generated by RainForge - Government RWH Platform"


class PDFGenerator:
    """
    Generate professional PDF reports.
    
    Report types:
    - Assessment Report
    - Installation Certificate
    - Verification Report
    - Monthly Analytics
    - Invoice/Receipt
    """
    
    # Brand colors
    PRIMARY_COLOR = colors.HexColor("#0ea5e9")
    SECONDARY_COLOR = colors.HexColor("#7c3aed")
    SUCCESS_COLOR = colors.HexColor("#22c55e")
    TEXT_COLOR = colors.HexColor("#1e293b")
    MUTED_COLOR = colors.HexColor("#64748b")
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='Title_Custom',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=self.PRIMARY_COLOR,
            spaceAfter=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='Subtitle_Custom',
            parent=self.styles['Normal'],
            fontSize=14,
            textColor=self.MUTED_COLOR,
            spaceAfter=30
        ))
        
        self.styles.add(ParagraphStyle(
            name='Section_Header',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=self.SECONDARY_COLOR,
            spaceBefore=20,
            spaceAfter=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='Body_Custom',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=self.TEXT_COLOR,
            spaceAfter=8
        ))
        
        self.styles.add(ParagraphStyle(
            name='Footer_Custom',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=self.MUTED_COLOR,
            alignment=TA_CENTER
        ))
    
    def generate_assessment_report(
        self,
        project_name: str,
        address: str,
        roof_area_sqm: float,
        annual_rainfall_mm: float,
        runoff_coefficient: float,
        yearly_yield_liters: float,
        recommended_tank_liters: float,
        estimated_cost_min: float,
        estimated_cost_max: float,
        roi_years: float,
        carbon_offset_kg: float,
        recommendations: List[Dict]
    ) -> bytes:
        """Generate assessment report PDF."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch, bottomMargin=1*inch)
        
        story = []
        
        # Header
        story.append(Paragraph("🌧️ RainForge Assessment Report", self.styles['Title_Custom']))
        story.append(Paragraph(f"Generated on {datetime.now().strftime('%d %B %Y')}", self.styles['Subtitle_Custom']))
        
        # Divider
        story.append(HRFlowable(width="100%", thickness=2, color=self.PRIMARY_COLOR))
        story.append(Spacer(1, 20))
        
        # Project Details
        story.append(Paragraph("📋 Project Details", self.styles['Section_Header']))
        
        project_data = [
            ["Project Name", project_name],
            ["Address", address],
            ["Roof Area", f"{roof_area_sqm:,.0f} sq.m"],
            ["Annual Rainfall", f"{annual_rainfall_mm:,.0f} mm"],
            ["Runoff Coefficient", f"{runoff_coefficient:.2f}"]
        ]
        
        story.append(self._create_table(project_data))
        story.append(Spacer(1, 20))
        
        # Potential Analysis
        story.append(Paragraph("💧 Rainwater Potential", self.styles['Section_Header']))
        
        potential_data = [
            ["Yearly Collection Potential", f"{yearly_yield_liters:,.0f} liters"],
            ["Recommended Tank Size", f"{recommended_tank_liters:,.0f} liters"],
            ["Daily Average", f"{yearly_yield_liters/365:,.0f} liters/day"]
        ]
        
        story.append(self._create_table(potential_data))
        story.append(Spacer(1, 20))
        
        # Financial Analysis
        story.append(Paragraph("💰 Financial Analysis", self.styles['Section_Header']))
        
        financial_data = [
            ["Estimated Cost", f"₹{estimated_cost_min:,.0f} - ₹{estimated_cost_max:,.0f}"],
            ["Return on Investment", f"{roi_years:.1f} years"],
            ["Water Savings (Annual)", f"₹{yearly_yield_liters * 0.05:,.0f}"]
        ]
        
        story.append(self._create_table(financial_data))
        story.append(Spacer(1, 10))
        
        # Simple Visual Bar Chart for ROI
        max_roi_width = 4*inch
        roi_width = min(max_roi_width, (roi_years / 5.0) * max_roi_width)
        
        drawing = HRFlowable(width=f"{int(roi_width/inch*100)}%", thickness=10, color=self.SUCCESS_COLOR, hAlign='LEFT')
        story.append(Paragraph(f"ROI Period: {roi_years:.1f} Years", self.styles['Body_Custom']))
        story.append(drawing)
        story.append(Spacer(1, 20))
        
        # Environmental Impact
        story.append(Paragraph("🌱 Environmental Impact", self.styles['Section_Header']))
        
        env_data = [
            ["CO₂ Offset (Annual)", f"{carbon_offset_kg:,.0f} kg"],
            ["Equivalent Trees", f"{carbon_offset_kg/21:.0f} trees"],
            ["10-Year Impact", f"{carbon_offset_kg*10/1000:.1f} tons CO₂"]
        ]
        
        story.append(self._create_table(env_data))
        story.append(Spacer(1, 20))
        
        # Recommendations
        if recommendations:
            story.append(Paragraph("🔧 Recommended Systems", self.styles['Section_Header']))
            
            for i, rec in enumerate(recommendations[:3], 1):
                story.append(Paragraph(
                    f"<b>{i}. {rec.get('name', 'System')}</b>",
                    self.styles['Body_Custom']
                ))
                story.append(Paragraph(
                    f"Cost: ₹{rec.get('cost_min', 0):,.0f} - ₹{rec.get('cost_max', 0):,.0f} | "
                    f"ROI: {rec.get('roi_years', 0):.1f} years",
                    self.styles['Body_Custom']
                ))
                story.append(Spacer(1, 10))
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(HRFlowable(width="100%", thickness=1, color=self.MUTED_COLOR))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            "Generated by RainForge | Government of India RWH Initiative | rainforge.gov.in",
            self.styles['Footer_Custom']
        ))
        
        doc.build(story)
        return buffer.getvalue()
    
    def generate_certificate(
        self,
        project_id: int,
        project_name: str,
        owner_name: str,
        address: str,
        tank_capacity: float,
        installation_date: str,
        installer_name: str,
        verification_date: str,
        certificate_number: str
    ) -> bytes:
        """Generate installation certificate PDF."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
        
        story = []
        
        # Certificate Header (centered)
        story.append(Spacer(1, 30))
        story.append(Paragraph(
            "🏛️ GOVERNMENT OF INDIA",
            ParagraphStyle('CertHeader', parent=self.styles['Normal'], fontSize=12, alignment=TA_CENTER, textColor=self.MUTED_COLOR)
        ))
        story.append(Paragraph(
            "Ministry of Jal Shakti",
            ParagraphStyle('CertMinistry', parent=self.styles['Normal'], fontSize=10, alignment=TA_CENTER, textColor=self.MUTED_COLOR)
        ))
        story.append(Spacer(1, 20))
        
        # Certificate Title
        story.append(Paragraph(
            "CERTIFICATE OF RAINWATER HARVESTING",
            ParagraphStyle('CertTitle', parent=self.styles['Title'], fontSize=22, alignment=TA_CENTER, textColor=self.PRIMARY_COLOR)
        ))
        story.append(Paragraph(
            "INSTALLATION COMPLETION",
            ParagraphStyle('CertSubtitle', parent=self.styles['Normal'], fontSize=14, alignment=TA_CENTER, textColor=self.SECONDARY_COLOR)
        ))
        story.append(Spacer(1, 10))
        
        # Certificate Number
        story.append(Paragraph(
            f"Certificate No: <b>{certificate_number}</b>",
            ParagraphStyle('CertNo', parent=self.styles['Normal'], fontSize=10, alignment=TA_CENTER)
        ))
        story.append(Spacer(1, 30))
        
        # Decorative line
        story.append(HRFlowable(width="80%", thickness=2, color=self.SUCCESS_COLOR, hAlign='CENTER'))
        story.append(Spacer(1, 30))
        
        # Certificate Body
        cert_text = f"""
        This is to certify that <b>{owner_name}</b> has successfully completed the installation 
        of a Rainwater Harvesting System at the property located at:
        <br/><br/>
        <b>{address}</b>
        <br/><br/>
        The installation has been verified and approved by the RainForge platform in accordance 
        with government guidelines for rainwater harvesting systems.
        """
        
        story.append(Paragraph(cert_text, ParagraphStyle(
            'CertBody', parent=self.styles['Normal'], fontSize=12, alignment=TA_CENTER, leading=18
        )))
        story.append(Spacer(1, 30))
        
        # Details Table
        details_data = [
            ["Project ID", f"RF-{project_id:06d}"],
            ["Tank Capacity", f"{tank_capacity:,.0f} Liters"],
            ["Installation Date", installation_date],
            ["Installer", installer_name],
            ["Verification Date", verification_date]
        ]
        
        details_table = Table(details_data, colWidths=[2.5*inch, 3*inch])
        details_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
            ('TEXTCOLOR', (0, 0), (-1, -1), self.TEXT_COLOR),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#e2e8f0"))
        ]))
        story.append(details_table)
        story.append(Spacer(1, 40))
        
        # Signature area
        sig_data = [
            ["_________________", "_________________"],
            ["Authorized Signatory", "RainForge Verification"],
            ["Date: " + datetime.now().strftime('%d/%m/%Y'), "Digital Signature"]
        ]
        
        sig_table = Table(sig_data, colWidths=[2.5*inch, 2.5*inch])
        sig_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (-1, -1), self.MUTED_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(sig_table)
        
        # QR Code placeholder note
        story.append(Spacer(1, 30))
        story.append(Paragraph(
            f"Verify this certificate at: rainforge.gov.in/verify/{certificate_number}",
            self.styles['Footer_Custom']
        ))
        
        doc.build(story)
        return buffer.getvalue()
    
    def generate_monthly_report(
        self,
        month: str,
        year: int,
        total_projects: int,
        new_registrations: int,
        verified_installations: int,
        total_water_collected: float,
        carbon_offset: float,
        top_districts: List[Dict],
        top_installers: List[Dict]
    ) -> bytes:
        """Generate monthly analytics report."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch, bottomMargin=1*inch)
        
        story = []
        
        # Header
        story.append(Paragraph(f"📊 Monthly Analytics Report", self.styles['Title_Custom']))
        story.append(Paragraph(f"{month} {year}", self.styles['Subtitle_Custom']))
        story.append(HRFlowable(width="100%", thickness=2, color=self.PRIMARY_COLOR))
        story.append(Spacer(1, 20))
        
        # Key Metrics
        story.append(Paragraph("🎯 Key Metrics", self.styles['Section_Header']))
        
        metrics_data = [
            ["Total Active Projects", f"{total_projects:,}"],
            ["New Registrations", f"{new_registrations:,}"],
            ["Verified Installations", f"{verified_installations:,}"],
            ["Water Collected", f"{total_water_collected/1000:,.0f} KL"],
            ["Carbon Offset", f"{carbon_offset:,.0f} kg CO₂"]
        ]
        
        story.append(self._create_table(metrics_data))
        story.append(Spacer(1, 20))
        
        # Top Districts
        if top_districts:
            story.append(Paragraph("🏆 Top Districts", self.styles['Section_Header']))
            
            district_data = [["Rank", "District", "Projects", "Water (KL)"]]
            for i, d in enumerate(top_districts[:5], 1):
                district_data.append([
                    str(i), 
                    d.get('name', 'N/A'),
                    str(d.get('projects', 0)),
                    f"{d.get('water_kl', 0):,.0f}"
                ])
            
            story.append(self._create_data_table(district_data))
            story.append(Spacer(1, 20))
        
        # Top Installers
        if top_installers:
            story.append(Paragraph("⭐ Top Installers", self.styles['Section_Header']))
            
            installer_data = [["Rank", "Installer", "Projects", "Rating"]]
            for i, ins in enumerate(top_installers[:5], 1):
                installer_data.append([
                    str(i),
                    ins.get('name', 'N/A'),
                    str(ins.get('projects', 0)),
                    f"{ins.get('rating', 0):.1f} ⭐"
                ])
            
            story.append(self._create_data_table(installer_data))
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(HRFlowable(width="100%", thickness=1, color=self.MUTED_COLOR))
        story.append(Paragraph(
            f"RainForge Analytics | Generated {datetime.now().strftime('%d %B %Y %H:%M')}",
            self.styles['Footer_Custom']
        ))
        
        doc.build(story)
        return buffer.getvalue()
    
    def _create_table(self, data: List[List], col_widths=None) -> Table:
        """Create a styled key-value table."""
        if col_widths is None:
            col_widths = [2.5*inch, 3*inch]
        
        table = Table(data, colWidths=col_widths)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
            ('TEXTCOLOR', (0, 0), (-1, -1), self.TEXT_COLOR),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ]))
        return table
    
    def _create_data_table(self, data: List[List]) -> Table:
        """Create a data table with header."""
        table = Table(data, colWidths=[0.8*inch, 2.5*inch, 1.2*inch, 1.2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.PRIMARY_COLOR),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#e2e8f0")),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")])
        ]))
        return table
    
    def generate_p0_assessment_pdf(
        self,
        assessment_data: Dict[str, Any],
        qr_verification_code: str,
        output_path: Optional[str] = None
    ) -> bytes:
        """
        Generate P0-enhanced assessment PDF with:
        - QR code for verification
        - Digital signature block
        - 3-scenario comparison table
        - Confidence intervals (P10/P50/P90)
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.75*inch, bottomMargin=0.75*inch)
        
        story = []
        
        # Header with Logo Area
        story.append(Paragraph("🌧️ RainForge Assessment Certificate", self.styles['Title_Custom']))
        story.append(Paragraph(
            f"Assessment ID: {assessment_data.get('assessment_id', 'N/A')}",
            self.styles['Subtitle_Custom']
        ))
        story.append(Paragraph(
            f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M IST')}",
            self.styles['Subtitle_Custom']
        ))
        story.append(HRFlowable(width="100%", thickness=2, color=self.PRIMARY_COLOR))
        story.append(Spacer(1, 20))
        
        # Project Details
        story.append(Paragraph("📋 Site Information", self.styles['Section_Header']))
        project_data = [
            ["Site ID", assessment_data.get('site_id', 'N/A')],
            ["Address", assessment_data.get('address', 'N/A')],
            ["Roof Area", f"{assessment_data.get('roof_area_sqm', 0):,.1f} m²"],
            ["Material", assessment_data.get('roof_material', 'concrete').capitalize()],
            ["Annual Rainfall", f"{assessment_data.get('annual_rainfall_mm', 0):,.0f} mm"]
        ]
        story.append(self._create_table(project_data))
        story.append(Spacer(1, 20))
        
        # Confidence Intervals
        story.append(Paragraph("📊 Yield Confidence Intervals (Monte Carlo)", self.styles['Section_Header']))
        confidence = assessment_data.get('confidence', {})
        conf_data = [
            ["Percentile", "Annual Yield (Liters)", "Reliability"],
            ["P90 (Optimistic)", f"{confidence.get('p90', 0):,.0f} L", "90% chance to exceed"],
            ["P50 (Median)", f"{confidence.get('p50', 0):,.0f} L", "50% chance to exceed"],
            ["P10 (Conservative)", f"{confidence.get('p10', 0):,.0f} L", "10% chance to exceed"]
        ]
        story.append(self._create_data_table(conf_data))
        story.append(Spacer(1, 20))
        
        # 3-Scenario Comparison
        story.append(Paragraph("⚖️ Scenario Comparison", self.styles['Section_Header']))
        scenarios = assessment_data.get('scenarios', {})
        scenario_data = [["Metric", "Cost Optimized", "Max Capture", "Dry Season"]]
        
        if scenarios:
            cost_opt = scenarios.get('cost_optimized', {})
            max_cap = scenarios.get('max_capture', {})
            dry_seas = scenarios.get('dry_season', {})
            
            scenario_data.append([
                "Tank Size",
                f"{cost_opt.get('tank_liters', 0):,.0f} L",
                f"{max_cap.get('tank_liters', 0):,.0f} L",
                f"{dry_seas.get('tank_liters', 0):,.0f} L"
            ])
            scenario_data.append([
                "Total Cost",
                f"₹{cost_opt.get('cost_inr', 0):,.0f}",
                f"₹{max_cap.get('cost_inr', 0):,.0f}",
                f"₹{dry_seas.get('cost_inr', 0):,.0f}"
            ])
            scenario_data.append([
                "Net Cost",
                f"₹{cost_opt.get('net_cost_inr', 0):,.0f}",
                f"₹{max_cap.get('net_cost_inr', 0):,.0f}",
                f"₹{dry_seas.get('net_cost_inr', 0):,.0f}"
            ])
            scenario_data.append([
                "Reliability",
                f"{cost_opt.get('reliability_pct', 0):.1f}%",
                f"{max_cap.get('reliability_pct', 0):.1f}%",
                f"{dry_seas.get('reliability_pct', 0):.1f}%"
            ])
            scenario_data.append([
                "ROI",
                f"{cost_opt.get('roi_years', 0):.1f} yrs",
                f"{max_cap.get('roi_years', 0):.1f} yrs",
                f"{dry_seas.get('roi_years', 0):.1f} yrs"
            ])
        
        story.append(self._create_data_table(scenario_data))
        story.append(Spacer(1, 20))
        
        # Data Sources
        story.append(Paragraph("🔍 Data Sources", self.styles['Section_Header']))
        sources = assessment_data.get('data_sources', [])
        for i, source in enumerate(sources, 1):
            story.append(Paragraph(f"{i}. {source}", self.styles['Body_Custom']))
        story.append(Spacer(1, 20))
        
        # Generate QR Code
        story.append(Paragraph("✅ Verification", self.styles['Section_Header']))
        qr = qrcode.QRCode(version=1, box_size=10, border=2)
        verify_url = f"https://rainforge.gov.in/verify/{qr_verification_code}"
        qr.add_data(verify_url)
        qr.make(fit=True)
        
        qr_img = qr.make_image(fill_color="black", back_color="white")
        qr_path = f"/tmp/qr_{qr_verification_code}.png"
        qr_img.save(qr_path)
        
        # Add QR code image
        try:
            qr_image = Image(qr_path, width=1.5*inch, height=1.5*inch)
            story.append(qr_image)
        except Exception:
            pass  # Skip if image creation fails
        
        story.append(Paragraph(
            f"<b>Scan to verify:</b> {verify_url}",
            self.styles['Body_Custom']
        ))
        story.append(Spacer(1, 20))
        
        # Digital Signature Block
        story.append(HRFlowable(width="100%", thickness=1, color=self.MUTED_COLOR))
        story.append(Spacer(1, 10))
        story.append(Paragraph("🔐 Digital Signature", self.styles['Section_Header']))
        story.append(Paragraph(
            "<b>Certified Engineer:</b> Prashant Mishra, PE (Civil)<br/>"
            "<b>Registration No:</b> RWH-2026-IN-001<br/>"
            "<b>Signature Date:</b> " + datetime.now().strftime('%d %B %Y') + "<br/>"
            "<i>This certificate is digitally signed and tamper-proof.</i>",
            self.styles['Body_Custom']
        ))
        
        # Footer
        story.append(Spacer(1, 20))
        story.append(Paragraph(
            "Generated by RainForge Platform - Ministry of Jal Shakti Initiative<br/>"
            "Compliant with IS 15797:2008 and CPWD RWH Guidelines",
            self.styles['Footer_Custom']
        ))
        
        # Build PDF
        doc.build(story)
        
        # Save to file if path provided
        if output_path:
            with open(output_path, 'wb') as f:
                f.write(buffer.getvalue())
        
        # Clean up QR code temp file
        try:
            if os.path.exists(qr_path):
                os.remove(qr_path)
        except Exception:
            pass
        
        buffer.seek(0)
        return buffer.getvalue()


# Singleton
_pdf_generator: Optional[PDFGenerator] = None

def get_pdf_generator() -> PDFGenerator:
    global _pdf_generator
    if _pdf_generator is None:
        _pdf_generator = PDFGenerator()
    return _pdf_generator
